version: '3.8'
services: 
  server:
    build: ./server
    ports: 
      - '5000:5000'
    env_file: 
      - './server/server.env'
    volumes: 
      - ./server:/app
      - /app/node_modules
  npm:
    image: node:16-alpine
    working_dir: /app
    stdin_open: true
    tty: true
    volumes: 
      - ./server:/app
    entrypoint: ["npm"]
